### ISSUE TITLE
The future of this library and the Energenie clone

### ISSUE THREAD

**Issue by webash** [whaleygeek/pyenergenie#102]
Not sure an issue is the right place for this discussion, but in lieu of chat or other discussion forums on GitHub, hey what the heck.

Originally I commented [on that PR in the Energenie repo](https://github.com/Energenie/pyenergenie/pull/1#issuecomment-446747644) *before* I came across your far more fresh repo here. I've since been pretty happy with this repo and it's progress, not to mention your responsiveness. 

However, you alluded to a future of the Energenie devices/libraries that may be worth discussing. Can you elaborate @whaleygeek?

**Comment by whaleygeek** [comment]
I have an open invite to visit Energenie soon and chat to them about them perhaps pulling all my changes into their repo. Both sides have been busy with other stuff so I've not had a chance to organise this yet, but will try soon.

**Comment by webash** [comment]
That's great to hear. Thanks for your commitment to this, I would've been stumped on my home energy monitoring project without your work here.

**Comment by iotic-labs-markwharton** [comment]
Top work as usual, @whaleygeek . It indirectly won our first funding round when we "magically" turned on a toaster in our investor's board room.
